site_name: GeaFlow Docs

theme:
  name: null
  custom_dir: './docs/.cinder'

plugins:
  - include-markdown

markdown_extensions:
  - toc:
      toc_depth: 4

python_version: 3.8 # use Python 3.8
jinja2:
  version: 3.0.0 # use Jinja2 3.0.0